### ISSUE TITLE
DW1820A Bluetooth does not work properly in some circumstances

### ISSUE THREAD

**Issue by ivmm** [osy86/HaC-Mini#125]
**Describe the bug**
The NUC8i7HVK has a network card for the 1820A (CN-08PKF4). EFI uses the 2.4.0 version and opens the 1820A support option. BIOS already disable ASPM.

Wifi can be driven directly, but there is a problem with Bluetooth, you can display Bluetooth, but you can't connect any devices.

![image](https://user-images.githubusercontent.com/2120462/68995829-1614c800-08cd-11ea-8fd6-d72a2021bf0c.png)

![image](https://user-images.githubusercontent.com/2120462/68995837-25941100-08cd-11ea-8e90-7aedc5ae3d6b.png)

**Expected behavior**
Successfully running Bluetooth.

**Configuration**
- HaC Mini version [e.g: 2.0]: 2.4
- OSX version [e.g: 10.14.6]: 10.15.1
- NUC model [e.g: NUC8i7HNK]: NUC8i7HNK
- Boot SSD model and protocol [e.g: Samsung EVO 860 1TB, SATA]:  Western Digital SN750 NVMe 512G.  System
- Second SSD model and protocol (if installed) [e.g: HP EX920 1TB, NVMe]: Hikvision C2000 1T NVMe Data
- First DIMM model [e.g: Patriot DDR4-2666 16GB]: TEAM (十铨
) VULCAN SO-DIMM DDR4 GAMING LAPTOP MEMORY 2666Mhz 16GB
- Second DIMM model (if installed): TEAM (十铨
) VULCAN SO-DIMM DDR4 GAMING LAPTOP MEMORY 2666Mhz 16GB
- Display port(s) used [e.g: USB-C, mini DP]: mini DP
- Display resolution(s) [e.g: 4K, 5K]: 4K

**Modifications**

None

**Panic log**

None

**Comment by goodbest** [comment]
I'm not sure if  extension `acfs` is related to bluetooth.

May you can check this page (mine is working fine):
<img width="600" alt="Screen Shot 2019-11-17 at 12 35 25" src="https://user-images.githubusercontent.com/1118401/69003085-d4b90280-0936-11ea-911d-9fe9ea05cc6c.png">

**Comment by ivmm** [comment]
![image](https://user-images.githubusercontent.com/2120462/69003614-55303100-0940-11ea-81d6-f2750d6be46f.png)
There is a Bluetooth information page, but you cannot connect to a Bluetooth device, you can view the device, but you cannot connect.

![image](https://user-images.githubusercontent.com/2120462/69003623-785ae080-0940-11ea-9378-d344ae0d858d.png)

PCI information page is empty

**Comment by lmshsqlc** [comment]
Are used to have this problem before I switched over to apples airport card From DW1830A. No matter I was on cold boot or warm boot, sometimes I will see devices in the Bluetooth panel but neither of them I can’t connect to. 
for example I have a Magic Trackpad. Normally the system will connect every time does it start up and I connected pop-up will show on screen. But sometimes even if I manually connect from Bluetooth panel it won’t connect but it tries to. 
There’s a thread from daliansky which I think is relevant to this problem. He implemented a delay for the Bluetooth firmware patch on wake. 
https://blog.daliansky.net/DW1820A_BCM94350ZAE-driver-inserts-the-correct-posture.html
And by the way I think this might need to file an issue on BrcmPatch repo.

**Comment by dickding** [comment]
Yes, I have the same problem with my dw-1820a(CN-08PKF4)...sometimes it works, but sometimes, you can see the device but can not connect.

osx-10.15.1, hacmini 2.4

**Comment by catalina86** [comment]
> I used to have this problem before I switched over to apples airport card From DW1830A. No matter I was on cold boot or warm boot, sometimes I will see devices in the Bluetooth panel but neither of them I can’t connect to.
> for example I have a Magic Trackpad. Normally the system will connect every time does it start up and I connected pop-up will show on screen. But sometimes even if I manually connect from Bluetooth panel it won’t connect but it tries to.
> There’s a thread from daliansky which I think is relevant to this problem. He implemented a delay for the Bluetooth firmware patch on wake.
> https://blog.daliansky.net/DW1820A_BCM94350ZAE-driver-inserts-the-correct-posture.html
> And by the way I think this might need to file an issue on BrcmPatch repo.

I have tried as you told, and it works!
I had the some problem as yours. I add the boot args to implement a delay for the Bluetooth firmware patch, which is just follow what the daliansky said in his blog.
I add "**bpr_probedelay=100 bpr_initialdelay=300 bpr_postresetdelay=300**" to the boot args. After that, I can use the DW1820A's bluetooth to connect my devices. It seems that the problem solved.
My device information is:
NUC version: NUC8i7HVK
macOS version: 10.15.1
HaC-Mini version: 2.4
DW1820A version: CN-08PKF4

**Comment by goodbest** [comment]
@catalina86 
Actually, these settings `bpr_probedelay=100 bpr_initialdelay=300 bpr_postresetdelay=300` is also listed in `acidanthera/BrcmPatchRAM` readme.
So I think it's quite reasonable.

**Comment by catalina86** [comment]
@goodbest 
Yep, I think this is a way to solve the problem. I've worked on it for a day. The result is fantastic for me. I think you @ivmm can try this solution.

**Comment by ivmm** [comment]
I added the relevant statement, but it didn't work. Bluetooth is still unable to connect to the device.

![image](https://user-images.githubusercontent.com/2120462/69008365-7450b200-0984-11ea-97f5-952e6781e25c.png)

**Comment by catalina86** [comment]
@ivmm 
Have you forgotten all the bluetooth devices after reboot into the OS? Forget the bluetooth devices and connect them again. I had the similar problem and solved in this way.

**Comment by ivmm** [comment]
I grew up removing all Bluetooth devices and restarting the system after turning off Bluetooth. I still can't connect to the device.

**Comment by catalina86** [comment]
@ivmm Maybe there is some differences between different cards. You can follow the README of the `acidanthera/BrcmPatchRAM` repo. It said:
> Note: Some with the typical "wake from sleep" problems are reporting success with: bpr_probedelay=100 bpr_initialdelay=300 bpr_postresetdelay=300. Or slightly longer delays: bpr_probedelay=200 bpr_initialdelay=400 bpr_postresetdelay=400.
You can change the delay time as the instruction said and try again. Wish you good luck.

**Comment by dickding** [comment]
Have you patched the thunderbolt?
I patched the thunderbolt, and found the machine sometimes won't boot, and the bluetooth didn't work properly.
After I uninstalled the thunderbolt patch, now the bluetooth works fine.

**Comment by ivmm** [comment]
@dickding  You are right, you can connect to Wi-Fi normally using native thunderbolt, thank you!

**Comment by goodbest** [comment]
Maybe there is some bug in BrcmPatch v2.5 itself? We'd better wait and see.

Some none-nuc D1820A users are reporting [mixed results].(https://www.insanelymac.com/forum/topic/339175-brcmpatchram2-for-1015-catalina-broadcom-bluetooth-firmware-upload/?page=11)

For me, I have some issue with the patch v2.5 on a dell hackintosh laptop under 10.14.6, but it works flawlessly with RehabMan's original patch (which is not working for 10.15)

**Comment by wittyofficer** [comment]
@ivmm I also had the same issue but adding `brcmfx-driver=2` argument to `boot-args` seems to solve it. 

`brcmfx-driver=2` enables the AirPortBrcmNIC kext in AirportBrcmFixup. You can refer to it in `acidanthera/AirportBrcmFixup` readme.

**Comment by chrisallen** [comment]
I am also running into this issue. Here are my boot-args and log of last boot.

boot-args = `alcid=11 shikigva=32 shiki-id=Mac-BE088AF8C5EB4FA2 -disablegfxfirmware brcmfx-country=NZ bpr_probedelay=100 bpr_initialdelay=300 bpr_postresetdelay=300` (I have even tried `brcmfx-driver=2` which made no difference)

```
chrisallen@Mac-mini ~ % log show --last boot | grep -i brcm
2019-12-10 10:24:09.231170+1300 0x10e      Default     0x0                  0      0    kernel: (IO80211Family) AirPort_BrcmNIC::init AirPortFamily_kexts-1565.4 "AirPortFamily_kexts-1565.4" Oct 17 2019 16:38:55
2019-12-10 10:24:09.231193+1300 0x10e      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 1.231191: AirPort_Brcm43XX:probe:, this[0x2050af1af38822d]  score[2048]
2019-12-10 10:24:09.231207+1300 0x10e      Default     0x0                  0      0    kernel: (IO80211Family) AirPort_BrcmNIC::init AirPortFamily_kexts-1565.4 "AirPortFamily_kexts-1565.4" Oct 17 2019 16:38:55
2019-12-10 10:24:09.231221+1300 0x10e      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 1.231220: AirPort_Brcm43XX:probe:, this[0x2050af1af38d22d]  score[1400]
2019-12-10 10:24:27.000203+1300 0x51c      Default     0x0                  0      0    kernel: (IO80211Family) AirPort_BrcmNIC::getSSIDData(): Get failure: APPLE80211_IOC_SSID: 6
2019-12-10 10:24:27.960332+1300 0x2fd      Error       0x0                  105    0    kextd: (IOKit) [com.apple.kext:kextlog] Unable to determine realpath for /Library/Extensions/BrcmFirmwareData.kext - failing.
2019-12-10 10:24:28.241350+1300 0x2fd      Error       0x0                  105    0    kextd: (IOKit) [com.apple.kext:kextlog] Unable to determine realpath for /Library/Extensions/BrcmFirmwareData.kext - failing.
2019-12-10 10:24:28.317356+1300 0x2fd      Error       0x0                  105    0    kextd: (IOKit) [com.apple.kext:kextlog] Unable to determine realpath for /Library/Extensions/BrcmFirmwareData.kext - failing.
2019-12-10 10:24:28.330864+1300 0x2fd      Error       0x0                  105    0    kextd: (IOKit) [com.apple.kext:kextlog] Unable to determine realpath for /Library/Extensions/BrcmFirmwareData.kext - failing.
2019-12-10 10:24:28.341125+1300 0x1be      Default     0x0                  0      0    kernel: (BrcmFirmwareData) BrcmPatchRAM: Loaded compressed embedded firmware for key "BCM4350C5_003.006.007.0222.4689_v8785".
2019-12-10 10:24:28.341386+1300 0x1be      Default     0x0                  0      0    kernel: (BrcmFirmwareData) BrcmPatchRAM: Decompressed firmware (12582 bytes --> 31740 bytes).
2019-12-10 10:24:28.341634+1300 0x1be      Default     0x0                  0      0    kernel: (BrcmFirmwareData) BrcmPatchRAM: Firmware is valid IntelHex firmware.
2019-12-10 10:24:28.641816+1300 0x1be      Default     0x0                  0      0    kernel: (BrcmPatchRAM3) BrcmPatchRAM: [0a5c:6412]: USB [C8FF2878CA0C v274] "BCM2045A0" by "Broadcom Corp"
2019-12-10 10:24:28.646036+1300 0x1be      Default     0x0                  0      0    kernel: (BrcmPatchRAM3) BrcmPatchRAM: [0a5c:6412]: Firmware upgrade not needed.
2019-12-10 10:24:28.646457+1300 0x1be      Default     0x0                  0      0    kernel: (BrcmPatchRAM3) BrcmPatchRAM: Processing time 0.304 seconds.
2019-12-10 10:24:28.660483+1300 0x432      Default     0x0                  0      0    kernel: (IO80211Family) IO80211VirtualInterface::AirPort_BrcmNIC_P2PInterface::init name <p2p0> role 1
2019-12-10 10:24:28.660824+1300 0x432      Default     0x0                  0      0    kernel: (IO80211Family) AirPort_BrcmNIC_P2PInterface::init <p2p> role 1
2019-12-10 10:24:29.721018+1300 0x432      Default     0x0                  0      0    kernel: (IO80211Family) IO80211VirtualInterface::AirPort_BrcmNIC_P2PInterface::init name <awdl0> role 4
2019-12-10 10:24:29.721024+1300 0x432      Default     0x0                  0      0    kernel: (IO80211Family) AirPort_BrcmNIC_P2PInterface::awdlAttachToBpf name <awdl0> role 4 successful attach to bpf type 147
2019-12-10 10:24:29.722767+1300 0x432      Default     0x0                  0      0    kernel: (IO80211Family) AirPort_BrcmNIC_P2PInterface::init <awdl> role 4
2019-12-10 10:24:29.742769+1300 0x88a      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 22.975573: wl0: setAWDL_PEER_TRAFFIC_REGISTRATION: active 0, roam_off: 1, err 0 roam_start_set 0 forced_roam_set 0
2019-12-10 10:24:30.018903+1300 0x81a      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 23.251707: wl0: setCIPHER_KEY: key == NULL, clear keys
2019-12-10 10:24:31.214157+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 24.446961: txpwr advertised by STA: min 16dbm max 38dbm
2019-12-10 10:24:31.240765+1300 0x1f7      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 24.473569: SetCryptoKey() bcmerr[0]:  ea[f0:9f:c2:6e:ab:7a]  T: keyIdx[0] keylen[16] flags[0x0002] algo[4] rxiv(hi[0x00000000] lo[0x0000])
2019-12-10 10:24:31.240952+1300 0x1f7      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 24.473756: SetCryptoKey() bcmerr[0]:  ea[00:00:00:00:00:00]  R: keyIdx[1] keylen[16] flags[0x0000] algo[4] rxiv(hi[0x00000000] lo[0x0000])
2019-12-10 10:24:36.504640+1300 0x5a2      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 28.436128: wl_awdl_cap: 0x2
2019-12-10 10:24:36.506388+1300 0x5a2      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 28.437876: AWDL Sync Enabled 1, data path state[1]
2019-12-10 10:24:36.506405+1300 0x5a2      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 28.437894: wl_awdl_cap: 0x2
2019-12-10 10:24:39.590955+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 31.522443: txpkt (MPDU) Complete
2019-12-10 10:24:39.590960+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 31.522449: FrameID: 0x720b
2019-12-10 10:24:39.590962+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) Seq: 0x0098
2019-12-10 10:24:39.590964+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) TxStatus: 0x010b
2019-12-10 10:24:39.590966+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC)
2019-12-10 10:24:39.590970+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 31.522459: ACK 0 IM 0 PM 1 Suppr 0 (None)
2019-12-10 10:24:39.590974+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 31.522463: CNT(rts_tx)=0 CNT(frag_tx_cnt)=15 CNT(cts_rx_cnt)=0
2019-12-10 10:24:39.590977+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 31.522467: DequeueTime: 0x00000000
2019-12-10 10:24:39.590980+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) LastTxTime: 0x007e0410
2019-12-10 10:24:39.590982+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) PHYTxErr:   0x0000
2019-12-10 10:24:39.590984+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) RxAckRSSI: 0x0083
2019-12-10 10:24:39.590986+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) RxAckSQ: 0x00ff
2019-12-10 10:24:39.590988+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC)
2019-12-10 10:24:39.590990+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 31.522479: Raw
2019-12-10 10:24:39.590992+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) [0]    1 Valid
2019-12-10 10:24:39.590994+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 31.522483: [2]    0 IM
2019-12-10 10:24:39.590996+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 31.522486: [3]    1 PM
2019-12-10 10:24:39.590998+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 31.522488: [7-4]  0 Suppr
2019-12-10 10:24:39.591001+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 31.522490: [14:8] 1 Ncons
2019-12-10 10:24:39.591003+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 31.522493: [15]   0 Acked
2019-12-10 10:24:39.591006+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 31.522496: txpktpend AC_BK 0 AC_BE 1 AC_VI 0 AC_VO 2 BCMC 0 ATIM 0
2019-12-10 10:24:39.753624+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 31.685110: txpkt (MPDU) Complete
2019-12-10 10:24:39.753629+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 31.685118: FrameID: 0x020b
2019-12-10 10:24:39.753633+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) Seq: 0x009c
2019-12-10 10:24:39.753636+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) TxStatus: 0x0103
2019-12-10 10:24:39.753639+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC)
2019-12-10 10:24:39.753643+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 31.685132: ACK 0 IM 0 PM 0 Suppr 0 (None)
2019-12-10 10:24:39.753648+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 31.685137: CNT(rts_tx)=0 CNT(frag_tx_cnt)=15 CNT(cts_rx_cnt)=0
2019-12-10 10:24:39.753653+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 31.685142: DequeueTime: 0x00000000
2019-12-10 10:24:39.753657+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) LastTxTime: 0x00807f7e
2019-12-10 10:24:39.753660+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) PHYTxErr:   0x0000
2019-12-10 10:24:39.753663+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) RxAckRSSI: 0x0083
2019-12-10 10:24:39.753666+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) RxAckSQ: 0x00ff
2019-12-10 10:24:39.753669+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC)
2019-12-10 10:24:39.753671+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 31.685161: Raw
2019-12-10 10:24:39.753674+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) [0]    1 Valid
2019-12-10 10:24:39.753677+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 31.685166: [2]    0 IM
2019-12-10 10:24:39.753680+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 31.685170: [3]    0 PM
2019-12-10 10:24:39.753684+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 31.685173: [7-4]  0 Suppr
2019-12-10 10:24:39.753687+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 31.685176: [14:8] 1 Ncons
2019-12-10 10:24:39.753690+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 31.685180: [15]   0 Acked
2019-12-10 10:24:39.753695+1300 0x212      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 31.685184: txpktpend AC_BK 0 AC_BE 4 AC_VI 0 AC_VO 1 BCMC 0 ATIM 0
2019-12-10 10:24:43.702073+1300 0x1323     Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 35.633560: AWDL Sync Enabled 0, data path state[1]
chrisallen@Mac-mini ~ %
```

Right now I see the Bluetooth menu and sometimes things show up, but I cannot connect to anything.

![Screen Shot 2019-12-10 at 10 46 36 AM](https://user-images.githubusercontent.com/203867/70475908-77c9fa00-1b3a-11ea-968d-68b2f1a33c80.png)


Here is what it looks like in System Profiler

![image](https://user-images.githubusercontent.com/203867/70477229-443c9f00-1b3d-11ea-83bc-8cea0095fdf7.png)
![image](https://user-images.githubusercontent.com/203867/70477263-5585ab80-1b3d-11ea-99a9-9cc86cdc0906.png)

**Comment by chrisallen** [comment]
I am also seeing the same issue with my DW1820A (part# CN-096JNT) where devices show up but will not connect.

System Profiler info

```
 Apple Bluetooth Software Version:	7.0.1f1
  Hardware, Features and Settings:
  Name:	Mac mini
  Address:	C8-FF-28-78-CA-0C
  Bluetooth Low Energy Supported:	Yes
  Handoff Supported:	Yes
  Instant Hot Spot Supported:	Yes
  Manufacturer:	Broadcom
  Transport:	USB
  Chipset:	Unknown (6e)
  Firmware Version:	v7 c4689
  Bluetooth Power:	On
  Discoverable:	On
  Connectable:	Yes
  Auto Seek Pointing:	On
  Remote wake:	On
  Vendor ID:	0x0A5C
  Product ID:	0x6412
  Bluetooth Core Spec:	4.1 (0x7)
  HCI Revision:	0x1251
  LMP Version:	4.1 (0x7)
  LMP Subversion:	0x6607
  Device Type (Major):	Computer
  Device Type (Complete):	Mac Portable
  Composite Class Of Device:	0x38010C
  Device Class (Major):	0x01
  Device Class (Minor):	0x03
  Service Class:	0x1C0
  Auto Seek Keyboard:	On
```

Here is the log from last boot.

`log show --last boot | grep -i brcmp`
```
2019-12-10 11:21:34.156660+1300 0x1be      Default     0x0                  0      0    kernel: (BrcmFirmwareData) BrcmPatchRAM: Loaded compressed embedded firmware for key "BCM4350C5_003.006.007.0222.4689_v8785".
2019-12-10 11:21:34.156882+1300 0x1be      Default     0x0                  0      0    kernel: (BrcmFirmwareData) BrcmPatchRAM: Decompressed firmware (12582 bytes --> 31740 bytes).
2019-12-10 11:21:34.157095+1300 0x1be      Default     0x0                  0      0    kernel: (BrcmFirmwareData) BrcmPatchRAM: Firmware is valid IntelHex firmware.
2019-12-10 11:21:34.257416+1300 0x1be      Default     0x0                  0      0    kernel: (BrcmPatchRAM3) BrcmPatchRAM: [0a5c:6412]: USB [C8FF2878CA0C v274] "BCM2045A0" by "Broadcom Corp"
2019-12-10 11:21:34.262492+1300 0x1be      Default     0x0                  0      0    kernel: (BrcmPatchRAM3) BrcmPatchRAM: [0a5c:6412]: Firmware upgrade not needed.
2019-12-10 11:21:34.262555+1300 0x1be      Default     0x0                  0      0    kernel: (BrcmPatchRAM3) BrcmPatchRAM: Processing time 0.105 seconds.
```

My issue appears to be the same as what this user mentions (https://www.tonymacx86.com/threads/the-solution-dell-dw1820a-broadcom-bcm94350zae-macos-15.288026/post-2042843) but I don't have Linux or Windows installed to dual boot into)

**Comment by chrisallen** [comment]
Does anyone know how to fix the issue of not being able to connect to detected devices?

**Comment by lmshsqlc** [comment]
> Does anyone know how to fix the issue of not being able to connect to detected devices?

It happens sometimes. Usually what I’m doing is perform a cold restart.  Maybe you can check this out as well. 
https://github.com/osy86/HaC-Mini/issues/125#issuecomment-554716058

**Comment by chrisallen** [comment]
I've reported this over at InsanelyMac (https://www.insanelymac.com/forum/topic/339175-brcmpatchram2-for-1015-catalina-broadcom-bluetooth-firmware-upload/?do=findComment&comment=2700139)

**Comment by goodbest** [comment]
@chrisallen The most reliable `temp` fix for the issue is to boot into windows first (which has the proper bluetooth driver installed), and then you can have your bluetooth everywhere in macos.

The reason may be related to firmware upload in those kexts (although hackintools says fw loaded)

**Comment by cuteluo1983** [comment]
I have the same Problem with DW1830,after i delete this file ( / Library / Preferences / com.apple.Bluetooth.plist) and restart ,the problem fixed.
Have a try... @ivmm

**Comment by iiicwx** [comment]
I had the same issue before, but a cache rebuild fixed it.

**Comment by zhxiyao** [comment]
> I had the same issue before, but a cache rebuild fixed it.

May you tell more specifically about how to rebuild the cache?

**Comment by iiicwx** [comment]
it was to rebuild the system and kext caches, I used KCPM Utility Pro  to do that.

**Comment by crhendo** [comment]
While WiFi has been working perfectly, Bluetooth is sporadic and very frustrating. I have tried all the suggestions (that I could apply) both here and on other threads but I always end up in the same predicament ie I can see the keyboard and mouse, I can click connect on both of them but they simply will not connect. I remove power for 24 hours and sometimes I can reconnect but eventually they simply disconnect again. 

My solution was to deselect the DW1820A in HaC Mini Installer, reboot and in insert my old original IOGear Bluetooth USB dongle. All my Bluetooth devices now behave as they should and surprisingly the DW1820A WiFi works OK without being selected in the installer.

**Comment by lmshsqlc** [comment]
> Warning! While Handoff and other features are working as they should, unlocking using my Apple Watch does not work and further investigation tells me that Bluetooth 4.2 is required for this feature. (IOGear is only 4.0)

You won’t get a flawless unlocking experience until you use an Apple airport card. Apple Airport card is the only that automatically keeps connections to accessories. Using a third party Bluetooth will give you unlock only once you’ve got it setup.

**Comment by JeffreyName** [comment]
@osy
I met same issue, and I observed one interesting thing.

Every time bluetooth works if the firmware upgrade is not needed.

working case:
`2020-01-29 21:16:15.850285+0800 0x1be      Default     0x0                  0      0    kernel: (BrcmFirmwareData) BrcmPatchRAM: Loaded compressed embedded firmware for key "BCM4350C5_003.006.007.0222.4689_v8785".
2020-01-29 21:16:15.850573+0800 0x1be      Default     0x0                  0      0    kernel: (BrcmFirmwareData) BrcmPatchRAM: Decompressed firmware (12582 bytes --> 31740 bytes).
2020-01-29 21:16:15.850806+0800 0x1be      Default     0x0                  0      0    kernel: (BrcmFirmwareData) BrcmPatchRAM: Firmware is valid IntelHex firmware.
2020-01-29 21:16:15.952112+0800 0x1be      Default     0x0                  0      0    kernel: (BrcmPatchRAM3) BrcmPatchRAM: [0a5c:6412]: USB [3052CB851AC2 v274] "BCM2045A0" by "Broadcom Corp"
2020-01-29 21:16:15.956899+0800 0x1be      Default     0x0                  0      0    kernel: (BrcmPatchRAM3) BrcmPatchRAM: [0a5c:6412]: Firmware upgrade not needed.
2020-01-29 21:16:15.956921+0800 0x1be      Default     0x0                  0      0    kernel: (BrcmPatchRAM3) BrcmPatchRAM: Processing time 0.105 seconds.`


not working case:
`2020-01-29 23:06:15.176768+0800 0x1bd      Default     0x0                  0      0    kernel: (BrcmFirmwareData) BrcmPatchRAM: Loaded compressed embedded firmware for key "BCM4350C5_003.006.007.0222.4689_v8785".
2020-01-29 23:06:15.176941+0800 0x1bd      Default     0x0                  0      0    kernel: (BrcmFirmwareData) BrcmPatchRAM: Decompressed firmware (12582 bytes --> 31740 bytes).
2020-01-29 23:06:15.177118+0800 0x1bd      Default     0x0                  0      0    kernel: (BrcmFirmwareData) BrcmPatchRAM: Firmware is valid IntelHex firmware.
2020-01-29 23:06:15.277478+0800 0x1bd      Default     0x0                  0      0    kernel: (BrcmPatchRAM3) BrcmPatchRAM: [0a5c:6412]: USB [3052CB851AC2 v274] "BCM2045A0" by "Broadcom Corp"
2020-01-29 23:06:15.653321+0800 0x1bd      Default     0x0                  0      0    kernel: (BrcmPatchRAM3) BrcmPatchRAM: [0a5c:6412]: Firmware upgrade completed successfully.
2020-01-29 23:06:15.653367+0800 0x1bd      Default     0x0                  0      0    kernel: (BrcmPatchRAM3) BrcmPatchRAM: Processing time 0.476 seconds.
`

**Comment by lmshsqlc** [comment]
> BTW, is there a way to bypass firmware loading?

Firmware must be loaded for 3rd party Bluetooth card, as windows driver also loads a firmware. Sometimes a reboot from windows can make bluetooth work because the firmware has already updated by windows driver. Checkout Brcmpatch manual for further information. 
An Apple airport card can guarantee your experience as they always works out of the box.

**Comment by JeffreyVIP** [comment]
> Firmware must be loaded for 3rd party Bluetooth card, as windows driver also loads a firmware. Sometimes a reboot from windows can make bluetooth work because the firmware has already updated by windows driver. Checkout Brcmpatch manual for further information.
> An Apple airport card can guarantee your experience as they always works out of the box.
I have only Hackintosh in the box, no windows or other system at all, single SSD and only MacOS v10.15.2 on it.
I guess the default firmware in the chipset is the same as what the patch are trying to load.

**Comment by lmshsqlc** [comment]
> I guess the default firmware in the chipset is the same as what the patch are trying to load.

The firmware is not in the chipset but in the Wi-Fi card itself. it has a Bluetooth firmware that needs to be updated every time it cold boots or it won’t work. Maybe it’s a bug related to brcmpatch. but when I was using a 3rd party card, a reboot might fix the problem.

**Comment by JeffreyVIP** [comment]
@osy86 Just tried release version 2.6, cache rebuild can't make bluetooth connection working,  so I can do nothing but re-install v2.5 to restore bluetooth back.

**Comment by osy86** [comment]
The brcm kexts were updated. If there’s an issue there I can’t do much to help.

**Comment by JeffreyVIP** [comment]
> The brcm kexts were updated. If there’s an issue there I can’t do much to help.

Understand, can you provide source of the brcm kexts so that I can report the issue I met?

**Comment by osy86** [comment]
https://github.com/acidanthera/bugtracker

**Comment by kinaschen** [comment]
I have the same problem with you when I install the DW1820A Card into the slot after my installation,that's why the problem accourd, tried several ways to solve that as using all the mothod above.
Till I realized I may try rest NVRAM as did on a commin Mac, So I reset NVRAM and it worked,both my MagicKeyborad2 and bt headphones .T_T
