### ISSUE TITLE
Menu borders rendered incorrectly in Big Sur

### ISSUE THREAD

**Issue by LockVer** [osy86/HaC-Mini#316]
![image](https://user-images.githubusercontent.com/3351118/90958321-44f84400-e4c6-11ea-8bf5-d43a9039c8d3.png)
hacmini：2.11
![image](https://user-images.githubusercontent.com/3351118/90958334-648f6c80-e4c6-11ea-856f-085d9d458735.png)

**Comment by goodbest** [comment]
The metal driver still has some bug.
<img width="183" alt="Screen Shot 2020-08-24 at 9 51 49 PM" src="https://user-images.githubusercontent.com/1118401/91052507-22943100-e654-11ea-8da5-830dd9050107.png">
<img width="173" alt="Screen Shot 2020-08-24 at 9 52 01 PM" src="https://user-images.githubusercontent.com/1118401/91052514-245df480-e654-11ea-9e64-081240e98605.png">

**Comment by willy880305** [comment]
@osy86 Has this problem been solved in V2.12? Thanks a lot

**Comment by osy86** [comment]
No

**Comment by goodbest** [comment]
To see if the menu borders issue has been solved, you can trying using the following kexts to replace the kexts bundled in 2.1.2.
https://github.com/goodbest/Polaris22Fixup/releases/tag/1.3.0mod

-----
By the way, after using the above kexts and solve the menu border issue, one may still suffers from the desktop issue(black desktop with green blocks, screenshot by @ccsnake ).
However, this was related to desktop wallpaper caches. You can try one of the following for this:
- Rebuild desktop wallpaper caches for current user. See `/Library/Caches/Desktop Pictures/<uuid>` 
- Create a new user
- Reinstall the system with proper kexts

**Comment by blanboom** [comment]
> To see if the menu borders issue has been solved, you can trying using the following kexts to replace the kexts bundled in 2.1.2.
> https://github.com/goodbest/Polaris22Fixup/releases/tag/1.3.0mod
> 
> By the way, after using the above kexts and solve the menu border issue, one may still suffers from the desktop issue(black desktop with green blocks, screenshot by @ccsnake ).
> However, this was related to desktop wallpaper caches. You can try one of the following for this:
> 
> * Rebuild desktop wallpaper caches for current user. See `/Library/Caches/Desktop Pictures/<uuid>`
> * Create a new user
> * Reinstall the system with proper kexts

After replacing this kext, the menu border issue has been solved. But Safari may crash while playing YouTube/BiliBili videos.

**Comment by goodbest** [comment]
> > To see if the menu borders issue has been solved, you can trying using the following kexts to replace the kexts bundled in 2.1.2.
> > https://github.com/goodbest/Polaris22Fixup/releases/tag/1.3.0mod
> > By the way, after using the above kexts and solve the menu border issue, one may still suffers from the desktop issue(black desktop with green blocks, screenshot by @ccsnake ).
> > However, this was related to desktop wallpaper caches. You can try one of the following for this:
> > 
> > * Rebuild desktop wallpaper caches for current user. See `/Library/Caches/Desktop Pictures/<uuid>`
> > * Create a new user
> > * Reinstall the system with proper kexts
> 
> After replacing this kext, the menu border issue has been solved. But Safari may crash while playing YouTube/BiliBili videos.
> 
> [com.apple.WebKit.WebContent.crash.txt](https://github.com/osy86/HaC-Mini/files/5225840/com.apple.WebKit.WebContent.crash.txt)

Confirm this new crash issue on my side.
So more work should be needed to solve the rendering issue.

**Comment by osy86** [comment]
Try other device IDs to see if it helps with the crash.

**Comment by lf-openthos** [comment]
> > > To see if the menu borders issue has been solved, you can trying using the following kexts to replace the kexts bundled in 2.1.2.
> > > https://github.com/goodbest/Polaris22Fixup/releases/tag/1.3.0mod
> > > By the way, after using the above kexts and solve the menu border issue, one may still suffers from the desktop issue(black desktop with green blocks, screenshot by @ccsnake ).
> > > However, this was related to desktop wallpaper caches. You can try one of the following for this:
> > > 
> > > * Rebuild desktop wallpaper caches for current user. See `/Library/Caches/Desktop Pictures/<uuid>`
> > > * Create a new user
> > > * Reinstall the system with proper kexts
> > 
> > 
> > After replacing this kext, the menu border issue has been solved. But Safari may crash while playing YouTube/BiliBili videos.
> > [com.apple.WebKit.WebContent.crash.txt](https://github.com/osy86/HaC-Mini/files/5225840/com.apple.WebKit.WebContent.crash.txt)
> 
> Confirm this new crash issue on my side.
> So more work should be needed to solve the rendering issue.

Fixed rendering problem, but with a noticeable performance problem.

**Comment by osy86** [comment]
I think your patch disables Metal acceleration. Check if Geekbench still lets you test Metal.

**Comment by goodbest** [comment]
> I think your patch disables Metal acceleration. Check if Geekbench still lets you test Metal.

Yes, the patch disables Metal. That's not what we want. So do not use my patch above.

**Comment by mr-vito** [comment]
> > I think your patch disables Metal acceleration. Check if Geekbench still lets you test Metal.
> 
> Yes, the patch disables Metal. That's not what we want. So do not use my patch above.

I just wanted to say that I tried your patch with HaC Mini 2.12 and it resulted in a black screen.

I have a 1080p monitor via HDMI, using Beta 2 (I think: 20A4300b).

Is there any progress on the Polaris22FixUp @osy86?

Thanks!

**Comment by osy86** [comment]
@mr-vito probably won’t have time to look into it this year. But even then there’s a chance it’s not fixable because of changes in Apple’s drivers.

**Comment by guoziwanghao** [comment]
Safari crashes repeatedly when opening some websites，close Safari's JavaScript will not crash，but online videos cannot be played

**Comment by osy86** [comment]
Is this only on the new beta that came out today? I haven’t had this issue.

**Comment by guoziwanghao** [comment]
> Is this only on the new beta that came out today? I haven’t had this issue.


After replacing Polaris22Fixup1.30mod

**Comment by osy86** [comment]
You should have read the comments above. Don’t use that mod.

**Comment by guoziwanghao** [comment]
> You should have read the comments above. Don’t use that mod.


Is there any specific way to solve the interface problem？

**Comment by osy86** [comment]
Again read all the previous comments.

https://github.com/osy86/HaC-Mini/issues/316#issuecomment-697557696

**Comment by redblue9771** [comment]
My 4K monitor will flicker when the mouse stops～

**Comment by wangfuco** [comment]
I have just updated to the official release 11.0.1. It seems like this issue is back. Using release v2.14.

**Comment by keatliang2005** [comment]
just an idea, if wondered this is about swiftui -> metal -> polaris22

**Comment by havvk** [comment]
This issue is fixed in 11.1 beta(20c5048k).

![截屏2020-11-21 下午6 10 10](https://user-images.githubusercontent.com/8110260/99874686-d80b5c00-2c24-11eb-9bce-8f9fda525b3e.png)

**Comment by crowtech420** [comment]
> This issue is fixed in 11.1 beta(20c5048k).
> 
> ![截屏2020-11-21 下午6 10 10](https://user-images.githubusercontent.com/8110260/99874686-d80b5c00-2c24-11eb-9bce-8f9fda525b3e.png)

For me, it is not fixed.
![image](https://user-images.githubusercontent.com/55730058/99875031-5a951b00-2c27-11eb-88e3-1e24fccf23f8.png)

**Comment by redblue9771** [comment]
I noticed that different resolutions can cause different problems.

**Comment by mr-vito** [comment]
> This issue is fixed in 11.1 beta(20c5048k).
> 
> ![截屏2020-11-21 下午6 10 10](https://user-images.githubusercontent.com/8110260/99874686-d80b5c00-2c24-11eb-9bce-8f9fda525b3e.png)

@havvk 

Are you using a different GPU  (Radeon RX 590 8GB)?

Unless you are spoofing it, that is not the dGPU of Hades Canyon.

**Comment by havvk** [comment]
Sorry, I forget to unplug the eGPU.

The menu border still broked when I connected display directly to NUC.

![截屏2020-11-21 下午7 11 41](https://user-images.githubusercontent.com/8110260/99875887-de520600-2c2d-11eb-906d-cd7e6f7537c1.png)

> @havvk
> 
> Are you using a different GPU (Radeon RX 590 8GB)?
> 
> Unless you are spoofing it, that is not the dGPU of Hades Canyon.

**Comment by keatliang2005** [comment]
> Sorry, I forgot to unplug the eGPU.
> 
> The menu border still broke when I connected display directly to NUC.
> 
> ![截屏2020-11-21 下午7 11 41](https://user-images.githubusercontent.com/8110260/99875887-de520600-2c2d-11eb-906d-cd7e6f7537c1.png)
> 
> > @havvk
> > 
> > Are you using a different GPU (Radeon RX 590 8GB)?
> > 
> > Unless you are spoofing it, that is not the dGPU of Hades Canyon.
> 
> 

What's your resolution?

**Comment by keatliang2005** [comment]
> > This issue is fixed in 11.1 beta(20c5048k).
> > ![截屏2020-11-21 下午6 10 10](https://user-images.githubusercontent.com/8110260/99874686-d80b5c00-2c24-11eb-9bce-8f9fda525b3e.png)
> 
> For me, it is not fixed.
> ![image](https://user-images.githubusercontent.com/55730058/99875031-5a951b00-2c27-11eb-88e3-1e24fccf23f8.png)

you using what resolution and display output port ?

**Comment by mr-vito** [comment]
> > at setup cause what type of render glitch.
> 
> * is it resolution ?
> * type of port ? USB-C, HDMI, Display port

The issue seems to stem from Lilu userspace patching. It was mentioned somewhere in [here](https://github.com/osy86/Polaris22Fixup/issues/8) and [here](https://dortania.github.io/OpenCore-Install-Guide/extras/big-sur/#up-to-date-kexts-bootloader-and-config-plist).

> Known issues
> With Big Sur, quite a bit broke. Mainly the following:
> 
> Lilu
> Mainly user-space patching has severely broke, meaning certain functionality may have broken

I am eagerly waiting for this to be fixed. Until then, we will have to wait...

**Comment by goodbest** [comment]
Please test this kext under Big Sur, and report any side effect.
[Polaris22Fixup.kext.zip](https://github.com/osy86/HaC-Mini/files/5579485/Polaris22Fixup.kext.zip)
<img width="244" alt="Screen Shot 2020-11-22 at 20 46 08" src="https://user-images.githubusercontent.com/1118401/99904092-c8af1000-2d03-11eb-8d51-139591c842d0.png">

For me, it fixes the menu borders issue in both 11.0.1 and 11.1 beta1.
And I can see the correct metal device in Geekbench 5 with normal score, which means the metal is working.
PS. I'm using Intel de/encoding option with the installer.


TL, dr:
What modification has this kext done:

- The original Big Sur use an statement:
`if somevalue <21, then do sth.`

- osy's polaris22 patch the binary to do the statement,
`if somevalue >=21, then do sth.` 
The logic is illustrated here: https://osy.gitbook.io/hac-mini-guide/details/metal-driver-fix
However it's working partially in big sur.

- So I replace the value 21 (the value's meaning is unknown yet).
`if somevalue >=0, then do sth.`
I haven't found any side effect yet. But I suppose a value between 0 and 21 would be better.

**Comment by crowtech420** [comment]
> Please test this kext under Big Sur, and report any side effect.
> [Polaris22Fixup.kext.zip](https://github.com/osy86/HaC-Mini/files/5579485/Polaris22Fixup.kext.zip)
> <img alt="Screen Shot 2020-11-22 at 20 46 08" width="244" src="https://user-images.githubusercontent.com/1118401/99904092-c8af1000-2d03-11eb-8d51-139591c842d0.png">
> 
> For me, it fixes the menu borders issue in both 11.0.1 and 11.1 beta1.
> And I can see the correct metal device in Geekbench 5 with normal score, which means the metal is working.
> PS. I'm using Intel de/encoding option with the installer. I also set the iGPU = enable in BIOS. Not sure if it's necessary
> 
> TL, dr:
> What modification has this kext done:
> 
> * The original Big Sur use an statement:
>   `if somevalue <21, then do sth.`
> * osy's polaris22 patch the binary to do the statement,
>   `if somevalue >=21, then do sth.`
>   The logic is illustrated here: https://osy.gitbook.io/hac-mini-guide/details/metal-driver-fix
>   However it's working partially in big sur.
> * So I replace the value 21 (the value's meaning is unknown yet).
>   `if somevalue >=0, then do sth.`
>   I haven't found any side effect yet. But I suppose a value between 0 and 21 would be better.

Can confirm that the menu border issue is fixed with this kext. Will observe for any side effects and will report here if I found any.

**Comment by redblue9771** [comment]
> Please test this kext under Big Sur, and report any side effect.
> [Polaris22Fixup.kext.zip](https://github.com/osy86/HaC-Mini/files/5579485/Polaris22Fixup.kext.zip)
> <img alt="Screen Shot 2020-11-22 at 20 46 08" width="244" src="https://user-images.githubusercontent.com/1118401/99904092-c8af1000-2d03-11eb-8d51-139591c842d0.png">
> 
> For me, it fixes the menu borders issue in both 11.0.1 and 11.1 beta1.
> And I can see the correct metal device in Geekbench 5 with normal score, which means the metal is working.
> PS. I'm using Intel de/encoding option with the installer. I also set the iGPU = enable in BIOS. Not sure if it's necessary
> 
> TL, dr:
> What modification has this kext done:
> 
> * The original Big Sur use an statement:
>   `if somevalue <21, then do sth.`
> * osy's polaris22 patch the binary to do the statement,
>   `if somevalue >=21, then do sth.`
>   The logic is illustrated here: https://osy.gitbook.io/hac-mini-guide/details/metal-driver-fix
>   However it's working partially in big sur.
> * So I replace the value 21 (the value's meaning is unknown yet).
>   `if somevalue >=0, then do sth.`
>   I haven't found any side effect yet. But I suppose a value between 0 and 21 would be better.

For me, it's effective.(4k resolution)

**Comment by keatliang2005** [comment]
> Please test this kext under Big Sur, and report any side effect.
> [Polaris22Fixup.kext.zip](https://github.com/osy86/HaC-Mini/files/5579485/Polaris22Fixup.kext.zip)
> <img alt="Screen Shot 2020-11-22 at 20 46 08" width="244" src="https://user-images.githubusercontent.com/1118401/99904092-c8af1000-2d03-11eb-8d51-139591c842d0.png">
> 
> For me, it fixes the menu borders issue in both 11.0.1 and 11.1 beta1.
> And I can see the correct metal device in Geekbench 5 with normal score, which means the metal is working.
> PS. I'm using Intel de/encoding option with the installer. I also set the iGPU = enable in BIOS. Not sure if it's necessary
> 
> TL, dr:
> What modification has this kext done:
> 
> * The original Big Sur use an statement:
>   `if somevalue <21, then do sth.`
> * osy's polaris22 patch the binary to do the statement,
>   `if somevalue >=21, then do sth.`
>   The logic is illustrated here: https://osy.gitbook.io/hac-mini-guide/details/metal-driver-fix
>   However it's working partially in big sur.
> * So I replace the value 21 (the value's meaning is unknown yet).
>   `if somevalue >=0, then do sth.`
>   I haven't found any side effect yet. But I suppose a value between 0 and 21 would be better.

After apply with the mod on macOS 10.0.1, the glitch for Window/Dialog box render glitch is resolved, had not notice any crash or bug.

will monitor and report back if anything issues came up.

**Comment by TheBigJam** [comment]
Can confirm that I did not notice any side effect due to the change. Rendering is correct. Good job as usual!

**Comment by evil4blue** [comment]
![DDA83537-EF72-4F5B-B7E6-E6231AAF7335_4_5005_c](https://user-images.githubusercontent.com/22591045/100303978-65bbb400-2f63-11eb-98e7-4d61c4ee51fa.jpeg)

The borders seem to be fixed, but there are still some issues.  Look at the folder icon for nextcloud, it's corrupt.  Dynamic desktop backgrounds still show up as green squares on my system.  Maybe it's something on my end, not sure, but this is definitely a step forward.  Thanks for all the work!

**Comment by youngoris** [comment]
same issue here, wait for resolution.

**Comment by PumaOsX** [comment]
> Please test this kext under Big Sur, and report any side effect.
> [Polaris22Fixup.kext.zip](https://github.com/osy86/HaC-Mini/files/5579485/Polaris22Fixup.kext.zip)
> <img alt="Screen Shot 2020-11-22 at 20 46 08" width="244" src="https://user-images.githubusercontent.com/1118401/99904092-c8af1000-2d03-11eb-8d51-139591c842d0.png">
> 
> For me, it fixes the menu borders issue in both 11.0.1 and 11.1 beta1.
> And I can see the correct metal device in Geekbench 5 with normal score, which means the metal is working.
> PS. I'm using Intel de/encoding option with the installer. I also set the iGPU = enable in BIOS. Not sure if it's necessary
> 
> TL, dr:
> What modification has this kext done:
> 
> * The original Big Sur use an statement:
>   `if somevalue <21, then do sth.`
> * osy's polaris22 patch the binary to do the statement,
>   `if somevalue >=21, then do sth.`
>   The logic is illustrated here: https://osy.gitbook.io/hac-mini-guide/details/metal-driver-fix
>   However it's working partially in big sur.
> * So I replace the value 21 (the value's meaning is unknown yet).
>   `if somevalue >=0, then do sth.`
>   I haven't found any side effect yet. But I suppose a value between 0 and 21 would be better.

Thanks my friend you solved me a big problem. I just mounted the EFI with clover the replaced the kext with yours and robot now it's everything ok. and metal work's perfect how you can see.
![Schermata 2020-11-28 alle 21 31 13](https://user-images.githubusercontent.com/75163969/100525547-0effe580-31c2-11eb-87df-e96d5d0aed47.png)

**Comment by nach0boss** [comment]
> > Please test this kext under Big Sur, and report any side effect.
> > [Polaris22Fixup.kext.zip](https://github.com/osy86/HaC-Mini/files/5579485/Polaris22Fixup.kext.zip)
> > <img alt="Screen Shot 2020-11-22 at 20 46 08" width="244" src="https://user-images.githubusercontent.com/1118401/99904092-c8af1000-2d03-11eb-8d51-139591c842d0.png">
> > For me, it fixes the menu borders issue in both 11.0.1 and 11.1 beta1.
> > And I can see the correct metal device in Geekbench 5 with normal score, which means the metal is working.
> > PS. I'm using Intel de/encoding option with the installer. I also set the iGPU = enable in BIOS. Not sure if it's necessary
> > TL, dr:
> > What modification has this kext done:
> > 
> > * The original Big Sur use an statement:
> >   `if somevalue <21, then do sth.`
> > * osy's polaris22 patch the binary to do the statement,
> >   `if somevalue >=21, then do sth.`
> >   The logic is illustrated here: https://osy.gitbook.io/hac-mini-guide/details/metal-driver-fix
> >   However it's working partially in big sur.
> > * So I replace the value 21 (the value's meaning is unknown yet).
> >   `if somevalue >=0, then do sth.`
> >   I haven't found any side effect yet. But I suppose a value between 0 and 21 would be better.
> 
> Thanks my friend you solved me a big problem. I just mounted the EFI with clover then replaced the kext with yours and reboot now it's everything ok..., and metal work's perfect how you can see.
> ![Schermata 2020-11-28 alle 21 31 13](https://user-images.githubusercontent.com/75163969/100525836-dd881980-31c3-11eb-95bf-d56c53d755f5.png)

How did you install this kext? I cant drag/drop to S/L/E and in L/E it shows no effect.

Upraded from Cataline to Big Sur 11.0.1

Thanks!

**Comment by TheBigJam** [comment]
> > > Please test this kext under Big Sur, and report any side effect.
> > > [Polaris22Fixup.kext.zip](https://github.com/osy86/HaC-Mini/files/5579485/Polaris22Fixup.kext.zip)
> > > <img alt="Screen Shot 2020-11-22 at 20 46 08" width="244" src="https://user-images.githubusercontent.com/1118401/99904092-c8af1000-2d03-11eb-8d51-139591c842d0.png">
> > > For me, it fixes the menu borders issue in both 11.0.1 and 11.1 beta1.
> > > And I can see the correct metal device in Geekbench 5 with normal score, which means the metal is working.
> > > PS. I'm using Intel de/encoding option with the installer. I also set the iGPU = enable in BIOS. Not sure if it's necessary
> > > TL, dr:
> > > What modification has this kext done:
> > > 
> > > * The original Big Sur use an statement:
> > >   `if somevalue <21, then do sth.`
> > > * osy's polaris22 patch the binary to do the statement,
> > >   `if somevalue >=21, then do sth.`
> > >   The logic is illustrated here: https://osy.gitbook.io/hac-mini-guide/details/metal-driver-fix
> > >   However it's working partially in big sur.
> > > * So I replace the value 21 (the value's meaning is unknown yet).
> > >   `if somevalue >=0, then do sth.`
> > >   I haven't found any side effect yet. But I suppose a value between 0 and 21 would be better.
> > 
> > 
> > Thanks my friend you solved me a big problem. I just mounted the EFI with clover then replaced the kext with yours and reboot now it's everything ok..., and metal work's perfect how you can see.
> > ![Schermata 2020-11-28 alle 21 31 13](https://user-images.githubusercontent.com/75163969/100525836-dd881980-31c3-11eb-95bf-d56c53d755f5.png)
> 
> How did you install this kext? I cant drag/drop to S/L/E and in L/E it shows no effect.
> 
> Upraded from Cataline to Big Sur 11.0.1
> 
> Thanks!

You have to exchange the file in your EFI/OC/Kext folder at your EFI partition. You can use Clover Configurator to mount this partition.

**Comment by PumaOsX** [comment]
> How did you install this kext? I cant drag/drop to S/L/E and in L/E it shows no effect.
> 
> Upraded from Cataline to Big Sur 11.0.1
> 
> Thanks!

So it's easy..., download Clover Configurator (find the last version on mackie100projects) then open it, find the voice mount EFI, select your macOS drive and select mount EFI, then select open EFI and go in the kext folder under OC and past the Polaris22Fixup.kext overwriting the old one... it's possible you need to insert your password to approve the copy.
Reboot and done.

**Comment by nach0boss** [comment]
> > How did you install this kext? I cant drag/drop to S/L/E and in L/E it shows no effect.
> > Upraded from Cataline to Big Sur 11.0.1
> > Thanks!
> 
> So it's easy..., download Clover Configurator (find the last version on mackie100projects) then open it, find the voice mount EFI, select your macOS drive and select mount EFI, then select open EFI and go in the kext folder under OC and past the Polaris22Fixup.kext overwriting the old one... it's possible you need to insert your password to approve the copy.
> Reboot and done.

I love you! Worked like a charm! The strange thing is, that I didn´t see it right away, as some wallpapers tend to give you the green squares while browsing through them. But at least the OS is usable now :) Looking forward to some great development down the road @keatliang2005 !

**Comment by bigfoot7375** [comment]
Can confirm that @goodbest solution is working.
Menu borders / Windows borders / Wallpaper / Radio buttons / Checkboxes are all fixed.
Thank you!

**Comment by Oosram** [comment]
wallpaper still not working,Desktop is black background, with green square as before

**Comment by nach0boss** [comment]
> wallpaper still not working,Desktop is black background, with green square as before

try changing the background, I thought the same but then went ahead and selected a new one and it worked

**Comment by Oosram** [comment]
> > wallpaper still not working,Desktop is black background, with green square as before
> 
> try changing the background, I thought the same but then went ahead and selected a new one and it worked
thank you, tried again, can work now, but still some of them can't show normally

**Comment by bigfoot7375** [comment]
This is my desktop with the new Polaris kext fix.
As can see:
Dynamic wallpaper - present
Windows borders / Checkboxes / Radio buttons - all OK
![image](https://user-images.githubusercontent.com/75070545/101018876-cf941900-3574-11eb-924b-b033a07bf01c.png)

**Comment by nach0boss** [comment]
> > > wallpaper still not working,Desktop is black background, with green square as before
> > 
> > 
> > try changing the background, I thought the same but then went ahead and selected a new one and it worked
> > thank you, tried again, can work now, but still some of them can't show normally

Yes,I have the same issue, some wallpapers work, some dont. But the system is "stable" so I can work with that for now.

**Comment by Oosram** [comment]
> > > > wallpaper still not working,Desktop is black background, with green square as before
> > > 
> > > 
> > > try changing the background, I thought the same but then went ahead and selected a new one and it worked
> > > thank you, tried again, can work now, but still some of them can't show normally
> 
> Yes,I have the same issue, "DARK" Wallpapers do not work, the rest does.

and also Dynamic wallpapers not showing properly, only can show the picture but no movement

**Comment by hksexybaby** [comment]
> Please test this kext under Big Sur, and report any side effect.
> [Polaris22Fixup.kext.zip](https://github.com/osy86/HaC-Mini/files/5579485/Polaris22Fixup.kext.zip)
> <img alt="Screen Shot 2020-11-22 at 20 46 08" width="244" src="https://user-images.githubusercontent.com/1118401/99904092-c8af1000-2d03-11eb-8d51-139591c842d0.png">
> 
> For me, it fixes the menu borders issue in both 11.0.1 and 11.1 beta1.
> And I can see the correct metal device in Geekbench 5 with normal score, which means the metal is working.
> PS. I'm using Intel de/encoding option with the installer. I also set the iGPU = enable in BIOS. Not sure if it's necessary
> 
> TL, dr:
> What modification has this kext done:
> 
> * The original Big Sur use an statement:
>   `if somevalue <21, then do sth.`
> * osy's polaris22 patch the binary to do the statement,
>   `if somevalue >=21, then do sth.`
>   The logic is illustrated here: https://osy.gitbook.io/hac-mini-guide/details/metal-driver-fix
>   However it's working partially in big sur.
> * So I replace the value 21 (the value's meaning is unknown yet).
>   `if somevalue >=0, then do sth.`
>   I haven't found any side effect yet. But I suppose a value between 0 and 21 would be better.

Thanks Good Job

https://github.com/osy86/HaC-Mini/files/5579485/Polaris22Fixup.kext.zip

can Easy Problem Solving

**Comment by SpookHCK** [comment]
> Please test this kext under Big Sur, and report any side effect.
> [Polaris22Fixup.kext.zip](https://github.com/osy86/HaC-Mini/files/5579485/Polaris22Fixup.kext.zip)
> <img alt="Screen Shot 2020-11-22 at 20 46 08" width="244" src="https://user-images.githubusercontent.com/1118401/99904092-c8af1000-2d03-11eb-8d51-139591c842d0.png">
> 
> For me, it fixes the menu borders issue in both 11.0.1 and 11.1 beta1.
> And I can see the correct metal device in Geekbench 5 with normal score, which means the metal is working.
> PS. I'm using Intel de/encoding option with the installer. I also set the iGPU = enable in BIOS. Not sure if it's necessary
> 
> TL, dr:
> What modification has this kext done:
> 
> * The original Big Sur use an statement:
>   `if somevalue <21, then do sth.`
> * osy's polaris22 patch the binary to do the statement,
>   `if somevalue >=21, then do sth.`
>   The logic is illustrated here: https://osy.gitbook.io/hac-mini-guide/details/metal-driver-fix
>   However it's working partially in big sur.
> * So I replace the value 21 (the value's meaning is unknown yet).
>   `if somevalue >=0, then do sth.`
>   I haven't found any side effect yet. But I suppose a value between 0 and 21 would be better.

So I did a clean install of BigSur having placed this kext on the install usb, and I got a perfect and clean install!
Everything appears to be working, I will test some more, as I get time. Thank you for trying to make something good happen for the community!

**Comment by Oosram** [comment]
> > 请在Big Sur下测试此kext，并报告任何副作用。
> > [Polaris22Fixup.kext.zip](https://github.com/osy86/HaC-Mini/files/5579485/Polaris22Fixup.kext.zip)
> > <img alt="截屏2020-11-22 at 20 46 08" width="244" src="https://user-images.githubusercontent.com/1118401/99904092-c8af1000-2d03-11eb-8d51-139591c842d0.png">
> > 对我来说，它修复了11.0.1和11.1 beta1中的菜单边框问题。
> > 而且我可以在Geekbench 5中看到正确的金属设备，其分数正常，这意味着金属正在工作。
> > PS。我在安装程序中使用Intel de / encoding选项。我还在BIOS中设置了iGPU = enable。不确定是否有必要
> > TL，博士：
> > 此kext做了哪些修改：
> > 
> > * 原始的Big Sur使用声明：
> >   `if somevalue <21, then do sth.`
> > * osy的polaris22对二进制文件进行修补以执行该语句，
> >   `if somevalue >=21, then do sth.`
> >   其逻辑在此处进行了说明：[https](https://osy.gitbook.io/hac-mini-guide/details/metal-driver-fix) : //osy.gitbook.io/hac-mini-guide/details/metal-driver-fix
> >   然而，它在一定程度上可以正常工作。
> > * 因此，我替换了值21（该值的含义尚不清楚）。
> >   `if somevalue >=0, then do sth.`
> >   我还没有发现任何副作用。但我认为0到21之间的值会更好。
> 
> 因此，我将Big Ext放置在安装USB上，进行了BigSur的全新安装，从而获得了完美而干净的安装！
> 一切似乎都正常，随着时间的推移，我将进行更多测试。感谢您尝试为社区带来好事！

how is it going now, does the Dynamic wallpapers showing ?any movement?

**Comment by TheBigJam** [comment]
Hi osy can you provide me a compiled  Version of 3.0.1? With bootmenue enabled?I Shot my System. Tganks alot Greetings Jan.
