### ISSUE TITLE
Front headphone jack does not output audio

### ISSUE THREAD

**Issue by osy86** [osy86/HaC-Mini#4]
The front headphone path seems to be correct but no sound is being outputted. Appears to be a codec init issue.

Linux init calls these functions:

`alc_update_coef_idx(codec, 0x4a, 1 << 15, 0); /* Combo jack auto trigger control */`
`snd_hda_codec_write(codec, hp_pin, 0,
			    AC_VERB_SET_AMP_GAIN_MUTE, AMP_OUT_MUTE);`
`snd_hda_codec_write(codec, hp_pin, 0,
			    AC_VERB_SET_PIN_WIDGET_CONTROL, PIN_OUT);`
`alc294_hp_init()`

This commit may be relevant: https://github.com/torvalds/linux/commit/bde1a7459623a66c2abec4d0a841e4b06cc88d9a#diff-6cb60ab78549a5b6838f746b9e128105

**Comment by osy86** [comment]
Running the verbs from `alc294_hp_init` and then manually resetting (restarting) allows headphone output to work on the next boot. However, microphone still does not work, and sound breaks again after sleep/wakeup or headphone unplug/replug. Additionally, the audio quality is poor and requires some additional adjustment.

**Comment by osy86** [comment]
[alsa-info.txt](https://github.com/osy86/HaC-Mini/files/3633492/alsa-info.txt)
[hdaemu-log.txt](https://github.com/osy86/HaC-Mini/files/3633493/hdaemu-log.txt)

Attaching alsa info and hda-emu output.

**Comment by osy86** [comment]
Fixed in https://github.com/acidanthera/AppleALC/releases/tag/1.4.2

**Comment by chrisallen** [comment]
@osy86 Should the front audio jack work for analog audio with the latest v2.4?

I see you close this saying it's fixed in AppleALC 1.4.2, but in the https://osy.gitbook.io/hac-mini-guide/ it reports `Analog Audio (back port only)`

Thanks in advanced :)

**Comment by osy86** [comment]
It should work. Microphone still doesn't work though. I will update the guide.

**Comment by chrisallen** [comment]
Thank you @osy86 :) Should it mute the rear port when the front is connected?

**Comment by chrisallen** [comment]
Ahh I just tested, and it works in reverse. If I plug speakers into the rear and headphones into the front, audio only comes out the rear port. If I then unplug the speakers from the rear port then the front port starts working.

**Comment by osy86** [comment]
Yeah I’m sure there’s a way to change that but I haven’t looked into it.

**Comment by chrisallen** [comment]
Could you reopen this GHI and edit the title to reflect the reversed behaviour? or should I raise a new GHI?

**Comment by osy86** [comment]
Yeah open a new one

**Comment by chrisallen** [comment]
Thanks. I have raised a new GHI here: https://github.com/osy86/HaC-Mini/issues/144
